### ISSUE TITLE
The pool layers

### ISSUE THREAD

**Issue by 77Chen** [xiaomengyc/ACoL#17]
Hi,
Thanks for sharing your code. 
We know that the kernel size of maxpool in the VGG network is 2*2, and the size of your network is 3*3, and the sride of the last two pool layers is 1. I want to know why use 3*3 pooling? And why the stride of the last two pool layers is 1?

**Comment by xiaomengyc** [comment]
There might be some divergences between the VGG paper and this implementation. Somehow, I reused the implementation of Torchvision which uses the pooling layer of 3*3 with stride=2. To increase the resolution of the final feature maps, I changed the stride to 1.  As you may have known, it is better to have a higher resolution to compute the final heatmaps, but anyway, increasing the resolution would significantly slow the training down.

I hope the above explanation can solve your problem.

**Comment by 77Chen** [comment]
I get it, thank you very much!
