### ISSUE TITLE
combining localization results with classification results

### ISSUE THREAD

**Issue by chaoyan1037** [xiaomengyc/ACoL#5]
Hi,
Thanks for you sharing your code! When I am reading your paper, I find one part before `4.3` that I do not understand.

`We further improve the localization performance by combining our localization results with the state-of-the-art classification results`

How did you use the classification result? Could you please briefly describe it? I am interested in this paper but new to this area.

**Comment by xiaomengyc** [comment]
Hi @chaoyan1037 ,
I'm sorry for the confusion in the paper. 
According to the metric, an image is considered to be successfully localized if (1)  this image is correctly classified; (2) the overlap of the predicted bbox is larger then 0.5. Therefore, we think some bboxes are correctly predicted, but they are misclassified. We use better classification results from some advanced networks, such as ResNet, DPN, etc. to obtain the highest localization accuracy. 
It is also notable. If the ground-truth classification results are applied for testing, the localization results are then not affected by the classification accuracy.  We can use this result to compare the pure localization performance of the networks. This method is also adopted in these two papers [Hide&Seek.](https://arxiv.org/pdf/1704.04232.pdf) and [SPG](https://arxiv.org/abs/1807.08902).

Thanks.

**Comment by chaoyan1037** [comment]
hi @xiaomengyc ,
I see! Thanks a lot for your clarification!
